-- liquibase formatted sql

-- changeset arunvaidhyanathan:1741018683771-1
CREATE TABLE "alert_mst" ("alert_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "alert_name" VARCHAR(255) NOT NULL, "description" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, CONSTRAINT "alert_mst_pkey" PRIMARY KEY ("alert_id"));

-- changeset arunvaidhyanathan:1741018683771-2
CREATE TABLE "alert_details_mst" ("alert_detail_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "alert_id" INTEGER, "detail_description" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, CONSTRAINT "alert_details_mst_pkey" PRIMARY KEY ("alert_detail_id"));

-- changeset arunvaidhyanathan:1741018683771-3
CREATE TABLE "business_role" ("role_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "role_name" VARCHAR(255) NOT NULL, "description" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, CONSTRAINT "business_role_pkey" PRIMARY KEY ("role_id"));

-- changeset arunvaidhyanathan:1741018683771-4
CREATE TABLE "alert_notes" ("note_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "alert_id" INTEGER, "note_text" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, CONSTRAINT "alert_notes_pkey" PRIMARY KEY ("note_id"));

-- changeset arunvaidhyanathan:1741018683771-5
CREATE TABLE "match_notes" ("match_note_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "alert_detail_id" INTEGER, "note_text" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, CONSTRAINT "match_notes_pkey" PRIMARY KEY ("match_note_id"));

-- changeset arunvaidhyanathan:1741018683771-6
CREATE TABLE "alert_audit" ("audit_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "alert_id" INTEGER, "user_id" INTEGER, "action" VARCHAR(255), "details" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, CONSTRAINT "alert_audit_pkey" PRIMARY KEY ("audit_id"));

-- changeset arunvaidhyanathan:1741018683771-7
CREATE TABLE "notes_audit" ("audit_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "note_id" INTEGER, "user_id" INTEGER, "action" VARCHAR(255), "details" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, CONSTRAINT "notes_audit_pkey" PRIMARY KEY ("audit_id"));

-- changeset arunvaidhyanathan:1741018683771-8
CREATE TABLE "business_units" ("unit_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "unit_name" VARCHAR(255) NOT NULL, "description" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, CONSTRAINT "business_units_pkey" PRIMARY KEY ("unit_id"));

-- changeset arunvaidhyanathan:1741018683771-9
CREATE TABLE "alert_attachments" ("attachment_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "alert_id" INTEGER, "file_name" VARCHAR(255) NOT NULL, "file_path" VARCHAR(255) NOT NULL, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, CONSTRAINT "alert_attachments_pkey" PRIMARY KEY ("attachment_id"));

-- changeset arunvaidhyanathan:1741018683771-10
CREATE TABLE "business_user" ("user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "username" VARCHAR(255) NOT NULL, "password" VARCHAR(255) NOT NULL, "email" VARCHAR(255), "role_id" INTEGER, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, CONSTRAINT "business_user_pkey" PRIMARY KEY ("user_id"));

-- changeset arunvaidhyanathan:1741018683771-11
CREATE TABLE "business_on_boarding" ("onboarding_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_id" INTEGER, "unit_id" INTEGER, "start_date" date, "end_date" date, "created_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, "modified_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() AT TIME ZONE 'utc'::text, CONSTRAINT "business_on_boarding_pkey" PRIMARY KEY ("onboarding_id"));

-- changeset arunvaidhyanathan:1741018683771-12
CREATE TABLE "flyway_schema_history" ("installed_rank" INTEGER NOT NULL, "version" VARCHAR(50), "description" VARCHAR(200) NOT NULL, "type" VARCHAR(20) NOT NULL, "script" VARCHAR(1000) NOT NULL, "checksum" INTEGER, "installed_by" VARCHAR(100) NOT NULL, "installed_on" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "execution_time" INTEGER NOT NULL, "success" BOOLEAN NOT NULL, CONSTRAINT "flyway_schema_history_pk" PRIMARY KEY ("installed_rank"));

-- changeset arunvaidhyanathan:1741018683771-13
ALTER TABLE "business_role" ADD CONSTRAINT "business_role_role_name_key" UNIQUE ("role_name");

-- changeset arunvaidhyanathan:1741018683771-14
CREATE INDEX "idx_business_user_username" ON "business_user"("username");

-- changeset arunvaidhyanathan:1741018683771-15
ALTER TABLE "business_user" ADD CONSTRAINT "business_user_username_key" UNIQUE ("username");

-- changeset arunvaidhyanathan:1741018683771-16
CREATE INDEX "flyway_schema_history_s_idx" ON "flyway_schema_history"("success");

-- changeset arunvaidhyanathan:1741018683771-17
ALTER TABLE "alert_attachments" ADD CONSTRAINT "alert_attachments_alert_id_fkey" FOREIGN KEY ("alert_id") REFERENCES "alert_mst" ("alert_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset arunvaidhyanathan:1741018683771-18
ALTER TABLE "alert_audit" ADD CONSTRAINT "alert_audit_alert_id_fkey" FOREIGN KEY ("alert_id") REFERENCES "alert_mst" ("alert_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset arunvaidhyanathan:1741018683771-19
ALTER TABLE "alert_details_mst" ADD CONSTRAINT "alert_details_mst_alert_id_fkey" FOREIGN KEY ("alert_id") REFERENCES "alert_mst" ("alert_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset arunvaidhyanathan:1741018683771-20
ALTER TABLE "alert_notes" ADD CONSTRAINT "alert_notes_alert_id_fkey" FOREIGN KEY ("alert_id") REFERENCES "alert_mst" ("alert_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset arunvaidhyanathan:1741018683771-21
ALTER TABLE "business_on_boarding" ADD CONSTRAINT "business_on_boarding_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "business_units" ("unit_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset arunvaidhyanathan:1741018683771-22
ALTER TABLE "business_on_boarding" ADD CONSTRAINT "business_on_boarding_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "business_user" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset arunvaidhyanathan:1741018683771-23
ALTER TABLE "business_user" ADD CONSTRAINT "business_user_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "business_role" ("role_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset arunvaidhyanathan:1741018683771-24
ALTER TABLE "match_notes" ADD CONSTRAINT "match_notes_alert_detail_id_fkey" FOREIGN KEY ("alert_detail_id") REFERENCES "alert_details_mst" ("alert_detail_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset arunvaidhyanathan:1741018683771-25
ALTER TABLE "notes_audit" ADD CONSTRAINT "notes_audit_note_id_fkey" FOREIGN KEY ("note_id") REFERENCES "alert_notes" ("note_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

